cd build
#cmake .. -DTRT_LIB_DIR=$TRT_LIB_PATH -DTRT_OUT_DIR=`pwd`/out -DBUILD_PARSERS=ON -DBUILD_SAMPLES=ON
cmake .. -DBUILD_PARSERS=OFF -DBUILD_SAMPLES=OFF -DTRT_LIB_DIR=${TENSORRT_LIB_PATH} -DTRTBIN_DIR=`pwd`/out \
-DBUILD_PLUGINS=ON -DCUB_ROOT_DIR=${CUB_PATH}
make -j20
